### ISSUE TITLE
HTML format seems to be different for International destinations

### ISSUE THREAD

**Issue by vinodc** [ezekg/swa-dashboard#10]
International flights such as [OAK <-> MEX](https://global.southwest.com/southwest/dyn/air/booking/availability?DATE_1=201701260000&DATE_2=201701270000&TRIP_TYPE=R&B_LOCATION_1=OAK&E_LOCATION_1=MEX&E_LOCATION_2=&IS_FLEXIBLE=FALSE&NB_ADT=1&NB_YCD=0&USE_DING=FALSE&USE_POINTS=FALSE&PROMO_CODE=&ENC=&ENCT=2&LANGUAGE=US&SITE=ADCQADCQ&MAX_AIR_AVAIL_DAYS=150&PORTAL_DOMAIN=&MARKETS=&int=) appear to have a different HTML format. The DOM shows that the tables are less clear and have IDs of the form `bNTable` where N = 0, 1, 2, ... rather than `#outboundFares`. The formats for the rows are different as well, so the `.product_price` isn't applicable. In my manual testing, I've only noticed this format appear for international destinations.

One other thing is that the link above seems to work fine, so submitting the form might be unnecessary since we can infer all the parameters for that link from the command line flags. I noticed that the form submission redirects to that link anyway. This would save a page load.

**Comment by ezekg** [comment]
I built it with domestic flights in mind, but a PR is welcome if you'd like to add another flag.

**Comment by ezekg** [comment]
International flights are not supported thanks to #31!
