### ISSUE TITLE
$Infinity price result for far future dates

### ISSUE THREAD

**Issue by dprothero** [ezekg/swa-dashboard#16]
Getting `$Infinity` for prices for this query:

```
swa --from 'SMF' --to 'PDX' --leave-date '06/30/2017' --return-date '07/05/2017' --passengers 4
```

**Comment by dprothero** [comment]
Wonder if the dates are too far out for the airline to return results.

**Comment by ezekg** [comment]
Yeah, this is a known issue: https://github.com/ezekg/swa-dashboard/issues/7, https://github.com/ezekg/swa-dashboard/issues/4. If you'd like to create a PR that adds validation for this situation and a note in the readme, feel free to!
