### ISSUE TITLE
npm link requires C++11 compiler

### ISSUE THREAD

**Issue by musicmunky** [ezekg/swa-dashboard#18]
Took me a while to figure out the issue, but you may want to add a bit to the README that libxmljs (and the node-gyp rebuild) requires a C++11 compiler, which the standard gcc/g++ compiler definitely is not.  You'll need to install that before attempting the "npm link" command, otherwise it will fail.  I was able to get this done using the steps outlined [here](http://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/).
I'm currently running CentOS 6.6, so I can't speak for other flavors of *nix, but I was definitely pulling out my hair for a while until my google-fu finally paid off!  
Anyway, this isn't a genuine "issue", but thought I'd bring it to your attention just in case.  Now that the tool is running properly it's great!  Thanks!

**Comment by wcrasta** [comment]
+1, I ran into a similar problem on Windows 10. The solution for me was to download [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools).

**Comment by ezekg** [comment]
Either of you want to add those notes to the readme?

**Comment by musicmunky** [comment]
Yeah if you wouldn't mind, just a small addendum about the C++11 compiler requirement would be great, thanks!

**Comment by ezekg** [comment]
Make a PR and I'll get it merged in.
