### ISSUE TITLE
sudo npm link

### ISSUE THREAD

**Issue by wcrasta** [ezekg/swa-dashboard#19]
Hi,

You might want to add in the README that if you get an error: `Error: EACCES: permission denied, unlink '/usr/lib/node_modules/swa-dashboard'`,  do `sudo npm link` instead of `npm link
`.  I was gonna make a pull request, but not 100% sure if sudo is **required**.

![Commands](https://cloud.githubusercontent.com/assets/7517395/21730395/1ef5a60a-d415-11e6-9152-f297ee476480.png)

**Comment by ezekg** [comment]
That usually means that you have `npm` installed incorrectly. It shouldn't need `sudo` to install node modules. It might be because it's trying to install into `/usr/lib/node_modules` and not `~/.npm-packages/lib/node_modules/`.

**Comment by wcrasta** [comment]
Thanks @ezekg . Turns out my NPM permissions are undesirable. If anyone else comes across this issue, see [this link](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

**Comment by ezekg** [comment]
No problem. Glad you got it figured out!
