### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by rusd11** [ezekg/swa-dashboard#21]
How difficult would it be to deploy this to Heroku for personal use? Users could deploy the application to their own Heroku instance and would be able to run from the cloud rather than their local machine. I wanted to reach out before I spent too much time forcing it to work if it's impractical. 

If you aren't familiar with Heroku, more info can be found here: https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction

**Comment by ezekg** [comment]
Not really what this project is for, but feel free to fork it and turn it into a node webapp! Right now it's just command line.

**Comment by ezekg** [comment]
I'd be impressed if somebody could do something like,

```bash
swa … | ansi-to-html > index.html
```

while setting up some type of web socket to refresh the page on each change, maybe using chokidar? Haha man, that would be beyond rad.
