### ISSUE TITLE
Monitor one-way flight?

### ISSUE THREAD

**Issue by ashgh** [ezekg/swa-dashboard#23]
Is it possible to configure this to monitor a one way flight? I tried putting the same date for depart and return, but it doesn't seem to work.

**Comment by ezekg** [comment]
You'll need to modify this flag: https://github.com/ezekg/swa-dashboard/blob/master/index.js?ts=2#L400 to whatever value SW needs when searching for one-way flights. It'd be cool if there was a command line flag for that, like `--one-way`. If you add that, create a PR and I'll merge it in.

**Comment by ezekg** [comment]
Added in e86f1a8e891697366f6125b11e09434517acf15b.
