### ISSUE TITLE
[Needs Documentation] Implicit reference contrib.log.add

### ISSUE THREAD

**Issue by thebearjew** [ezekg/swa-dashboard#24]
Hey!

Currently implementing #23 and was reading through the code and landed on an interesting  documentation goose chase with **blessed** and **contrib**.

I'm mostly writing this to share because I thought it was interesting and I'll be adding the relevant documentation (comments) when I've completed #23.
Disclaimer: I have no previous experience with blessed or contrib, so if this widely known information please tell me!

When reading the following lineI was a bit confused.
[index.js:321](https://github.com/ezekg/swa-dashboard/blob/master/index.js#L321)

```js
  /**
   * Display settings
   *
   * @param {Arr} config
   *
   * @return {Void}
   */
  settings(config) {
    config.forEach((c) => this.widgets.settings.add(c))
  }
```

At first it looked like the `settings` Object literal had some magical `add(value)` method on it.
Then I saw where/how the original values of `map: { ... }`, `settings: { ... }`, `graph: { ... }` were being replaced by contrib widgets.
[index.js:222-233](https://github.com/ezekg/swa-dashboard/blob/master/index.js#L222-L233)

```js
    for (let name in widgets) {
      let widget = widgets[name]
     
     // We're replacing the object literal for each widget previously defined on this.widgets
     // with a contrib widget object initialized by this.grid.set where this.grid is a contrib grid.
      this.widgets[name] = this.grid.set(
        widget.size.top,
        widget.size.left,
        widget.size.height,
        widget.size.width,
        widget.type,
        widget.options
      )
    }
```

Then I took at look at `contrib.log` which only defines a [Rolling Log](https://github.com/yaronn/blessed-contrib#rolling-log) widget that **does not have log.add(value)**.

Time to look at the source code!
[blessed-contrib/lib/widget/log.js:30](https://github.com/yaronn/blessed-contrib/blob/master/lib/widget/log.js#L30)

```js
var blessed = require('blessed')
   , Node = blessed.Node
   , List = blessed.List  

function Log(options) {
    // ... implementation
}

// Aha!
Log.prototype.__proto__ = List.prototype;
```

Lo and behold... [List → Methods → .add](https://github.com/chjj/blessed#methods-7) inherits from ScrollableText.
[blessed/lib/widgets/list.js:295](https://github.com/chjj/blessed/blob/master/lib/widgets/list.js#L294)

```js
// Finally!
Log.prototype.log =
Log.prototype.add = function() {
    // ... implementation
};
```

**Conclusion**: Either you dug through all this and chose to use `.add`, or you just guessed and got lucky 😛 - probably past experience with blessed I would assume.

But seriously, I'll throw in a few comments to disambiguate this method naming.

--

**Edit**: Corrected reference to Log. Actual interested `add()` method is from List as @ezekg pointed out below.

**Comment by ezekg** [comment]
Yeah, I didn't document anything because I didn't expect this lib to get so popular. Contrib's log actually inherits from `List`, not `Log`. [List has an `add()` method](https://github.com/chjj/blessed/blob/master/lib/widgets/list.js#L294) that bypasses all of contrib's additional logging logic, so I probably just chose to use that. In the end, I probably should have used List directly, but maybe I had a good reason not to and I just can't remember.

I didn't have any prior experience with blessed, just learned as I went. 👍

**Comment by thebearjew** [comment]
Awesome. Thanks for the info.

I actually did find List's `add()` method and I guess I wrote this incorrectly (so many L things).

Thanks for the clarification!

**Comment by ezekg** [comment]
Added in e86f1a8e891697366f6125b11e09434517acf15b.
