### ISSUE TITLE
Twilio

### ISSUE THREAD

**Issue by austinvernsonger** [ezekg/swa-dashboard#27]
Where do you set your Twilio info?

**Comment by ezekg** [comment]
Push the environment variables in your `~/.bash_profile`, then run `source ~/.bash_profile` or restart your terminal. The dashboard will automatically pick them up.

**Comment by LootenPlunder** [comment]
For windows users that find themselves here, the easiest thing is to create a batch file to set your twilio vars and run your swa command (.bat):

`@echo off

set TWILIO_ACCOUNT_SID=w455w4w46u6...
set TWILIO_AUTH_TOKEN=25gh2345...
set TWILIO_PHONE_FROM=+1720...
set TWILIO_PHONE_TO=+1303...

swa --from etc etc`

You could set the variables each time you run CMD or powershell but that's a pain.

**Comment by ezekg** [comment]
@LootenPlunder would you want to make a PR with a mention of that in the readme?

**Comment by LootenPlunder** [comment]
Sure. I'm super new at both node and github so I'll try and see how it goes.

**Comment by ezekg** [comment]
@LootenPlunder no problem. Let me know if you need any help! You could probably just update the readme directly from within GitHub using their UI. 🙂
