### ISSUE TITLE
Dependency Issues getting this on Raspbian

### ISSUE THREAD

**Issue by cdroby** [ezekg/swa-dashboard#38]
I'll post some more data later, but wanted to see if there were known workarounds for this on Raspbian. Several dependency issues with libxmljs and osmosis being built by node-gyp. I've tried a slew of versions of nodejs, npm, etc. but no luck so far.

What are libxmljs and osmosis used for in the script? If it's pieces like the visuals, perhaps I can remove those and get it up and running (not so worried about the visuals).

Thanks!

**Comment by ezekg** [comment]
Osmosis is used for scraping, which has a dep on libxml. Take a look at the troubleshooting section in the readme, as I believe it has a solution for the libxml issue.

**Comment by cdroby** [comment]
Worked through that already. It doesn't appear that it's able to find the libxmljs for arm/debian. I don't have access to the pi at the moment to get the exact errors (will update this evening).

**Comment by cdroby** [comment]
Ok sorry for the delay, here's the output in full:

Fresh install of Raspbian, post update and post upgrade:
Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global marked@0.3.6 should be installed with -g

> libxmljs@0.18.4 install /home/pi/Public/swa-dashboard/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-arm.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-arm.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@6.9.5 (node-v48 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-arm.tar.gz 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/Public/swa-dashboard/node_modules/libxmljs/.node-gyp"
gyp http GET https://nodejs.org/download/release/v6.9.5/node-v6.9.5-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.9.5/node-v6.9.5-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v6.9.5/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v6.9.5/SHASUMS256.txt
make: Entering directory '/home/pi/Public/swa-dashboard/node_modules/libxmljs/build'
make: *** No rule to make target '../.node-gyp/6.9.5/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/pi/Public/swa-dashboard/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/pi/Public/swa-dashboard/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/pi/Public/swa-dashboard/node_modules/libxmljs/build/Release"
gyp ERR! cwd /home/pi/Public/swa-dashboard/node_modules/libxmljs
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/pi/Public/swa-dashboard/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/pi/Public/swa-dashboard/node_modules/libxmljs/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/Public/swa-dashboard/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.38-v7+
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/pi/Public/swa-dashboard/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/pi/Public/swa-dashboard/node_modules/libxmljs
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/pi/Public/swa-dashboard/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/pi/Public/swa-dashboard/node_modules/libxmljs/build/Release' (1)
swa-dashboard@1.0.0 /home/pi/Public/swa-dashboard
├── airports@1.0.0 
├── blessed@0.1.81 
├─┬ blessed-contrib@3.5.5 
│ ├── ansi-term@0.0.2 
│ ├─┬ drawille-canvas-blessed-contrib@0.1.3 
│ │ ├── bresenham@0.0.3 
│ │ ├── drawille-blessed-contrib@1.0.0 
│ │ └── gl-matrix@2.3.2 
│ ├── lodash@4.17.4 
│ ├─┬ map-canvas@0.1.5 
│ │ └─┬ xml2js@0.4.17 
│ │   ├── sax@1.2.2 
│ │   └── xmlbuilder@4.2.1 
│ ├── marked@0.3.6 
│ ├─┬ marked-terminal@1.7.0 
│ │ ├─┬ cardinal@1.0.0 
│ │ │ ├── ansicolors@0.2.1 
│ │ │ └─┬ redeyed@1.0.1 
│ │ │   └── esprima@3.0.0 
│ │ ├─┬ cli-table@0.3.1 
│ │ │ └── colors@1.0.3 
│ │ ├── lodash.assign@4.2.0 
│ │ └─┬ node-emoji@1.5.1 
│ │   └── string.prototype.codepointat@0.2.0 
│ ├─┬ memory-streams@0.1.0 
│ │ └─┬ readable-stream@1.0.34 
│ │   ├── core-util-is@1.0.2 
│ │   ├── inherits@2.0.3 
│ │   ├── isarray@0.0.1 
│ │   └── string_decoder@0.10.31 
│ ├── memorystream@0.3.1 
│ ├─┬ picture-tube@0.0.4 
│ │ ├── buffers@0.1.1 
│ │ ├── charm@0.1.2 
│ │ ├─┬ event-stream@0.9.8 
│ │ │ └── optimist@0.2.8 
│ │ ├─┬ optimist@0.3.7 
│ │ │ └── wordwrap@0.0.3 
│ │ ├── png-js@0.1.1 
│ │ └── request@2.9.203 
│ ├─┬ request@2.79.0 
│ │ ├── aws-sign2@0.6.0 
│ │ ├── aws4@1.6.0 
│ │ ├── caseless@0.11.0 
│ │ ├─┬ combined-stream@1.0.5 
│ │ │ └── delayed-stream@1.0.0 
│ │ ├── extend@3.0.0 
│ │ ├── forever-agent@0.6.1 
│ │ ├─┬ form-data@2.1.2 
│ │ │ └── asynckit@0.4.0 
│ │ ├─┬ har-validator@2.0.6 
│ │ │ ├─┬ commander@2.9.0 
│ │ │ │ └── graceful-readlink@1.0.1 
│ │ │ ├─┬ is-my-json-valid@2.15.0 
│ │ │ │ ├── generate-function@2.0.0 
│ │ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ │ └── is-property@1.0.2 
│ │ │ │ ├── jsonpointer@4.0.1 
│ │ │ │ └── xtend@4.0.1 
│ │ │ └─┬ pinkie-promise@2.0.1 
│ │ │   └── pinkie@2.0.4 
│ │ ├─┬ hawk@3.1.3 
│ │ │ ├── boom@2.10.1 
│ │ │ ├── cryptiles@2.0.5 
│ │ │ ├── hoek@2.16.3 
│ │ │ └── sntp@1.0.9 
│ │ ├─┬ http-signature@1.1.1 
│ │ │ ├── assert-plus@0.2.0 
│ │ │ ├─┬ jsprim@1.3.1 
│ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ └── verror@1.3.6 
│ │ │ └─┬ sshpk@1.10.2 
│ │ │   ├── asn1@0.2.3 
│ │ │   ├── assert-plus@1.0.0 
│ │ │   ├── bcrypt-pbkdf@1.0.1 
│ │ │   ├─┬ dashdash@1.14.1 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── ecc-jsbn@0.1.1 
│ │ │   ├─┬ getpass@0.1.6 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── jodid25519@1.0.2 
│ │ │   ├── jsbn@0.1.1 
│ │ │   └── tweetnacl@0.14.5 
│ │ ├── is-typedarray@1.0.0 
│ │ ├── isstream@0.1.2 
│ │ ├── json-stringify-safe@5.0.1 
│ │ ├─┬ mime-types@2.1.14 
│ │ │ └── mime-db@1.26.0 
│ │ ├── oauth-sign@0.8.2 
│ │ ├── qs@6.3.0 
│ │ ├── stringstream@0.0.5 
│ │ ├─┬ tough-cookie@2.3.2 
│ │ │ └── punycode@1.4.1 
│ │ ├── tunnel-agent@0.4.3 
│ │ └── uuid@3.0.1 
│ ├─┬ sparkline@0.1.2 
│ │ ├── here@0.0.2 
│ │ └─┬ nopt@2.1.2 
│ │   └── abbrev@1.1.0 
│ ├─┬ strip-ansi@3.0.1 
│ │ └── ansi-regex@2.1.1 
│ ├── term-canvas@0.0.5 
│ └── x256@0.0.2 
├─┬ chalk@1.1.3 
│ ├── ansi-styles@2.2.1 
│ ├── escape-string-regexp@1.0.5 
│ ├── has-ansi@2.0.0 
│ └── supports-color@2.0.0 
├── chalk-rainbow@1.0.0 
├── date-format@0.0.2 
├─┬ pretty-ms@2.1.0 
│ ├─┬ is-finite@1.0.2 
│ │ └── number-is-nan@1.0.1 
│ ├── parse-ms@1.0.1 
│ └── plur@1.0.0 
└─┬ twilio@2.11.1 
  ├── deprecate@0.1.0 
  ├─┬ jsonwebtoken@5.4.1 
  │ ├─┬ jws@3.1.4 
  │ │ ├── base64url@2.0.0 
  │ │ ├─┬ jwa@1.1.5 
  │ │ │ ├── buffer-equal-constant-time@1.0.1 
  │ │ │ └── ecdsa-sig-formatter@1.0.9 
  │ │ └── safe-buffer@5.0.1 
  │ └── ms@0.7.1 
  ├── q@0.9.7 
  ├─┬ request@2.74.0 
  │ ├─┬ bl@1.1.2 
  │ │ └─┬ readable-stream@2.0.6 
  │ │   ├── isarray@1.0.0 
  │ │   ├── process-nextick-args@1.0.7 
  │ │   └── util-deprecate@1.0.2 
  │ ├─┬ form-data@1.0.1 
  │ │ └── async@2.1.4 
  │ ├── node-uuid@1.4.7 
  │ └── qs@6.2.1 
  ├── scmp@0.0.3 
  ├── string.prototype.startswith@0.2.0 
  └── underscore@1.8.3 

npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/sbin/npm" "link"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.4 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.4 install script 'node-pre-gyp install --fallback-to-build --loglevel http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by cdroby** [comment]
I can't recall how, but I have managed to get libxmljs installed, but then couldn't get gyp-node to work...

**Comment by ezekg** [comment]
Okay, are you getting a different error now?

**Comment by cdroby** [comment]
Same error.

**Comment by ezekg** [comment]
I think the issue may be that you're running `npm link` with sudo. [Try adding the `--unsafe-perm` flag](https://github.com/nodejs/node-gyp/issues/454), and if that doesn't work, you may need to install Node correctly to where it doesn't need sudo.

Before you do that, try removing your `node_modules` directory as well. You may also need to clear the node-gyp directory with `rm -rf /root/.node-gyp/`.

**Comment by cdroby** [comment]
Showing my lack of expertise here, but nvm had 0.10.26 installed. I updated it to be 6.9.5 and tried the whole thing over after clearing out both node and node-gyp and with the --unsafe-perm flag.

Needless to say it finally worked. Chalk this up to me being not great at installation and clearing of old node versions that came with the pi...

**Comment by ezekg** [comment]
Haha no problem. Glad you got it figured out. 👍
