### ISSUE TITLE
connectivity issues?

### ISSUE THREAD

**Issue by natemwilson** [ezekg/swa-dashboard#4]
I ran this command:
`swa --from 'EWR' --to 'LAX' --leave-date '06/01/2017' --return-date '07/01/2017' --passengers 1 --interval 1`

and got this in my dashboard.. any idea why I'm not connecting?

<img width="979" alt="screen shot 2017-01-02 at 11 24 44 am" src="https://cloud.githubusercontent.com/assets/10066574/21592769/2bc32bc6-d0de-11e6-903a-a2e6658363ea.png">

**Comment by ezekg** [comment]
It's actually because you can't book that far out in advance. There's no validation for this script, so that's why you're seeing the `$Infinity` prices for requests like this.

![image](https://cloud.githubusercontent.com/assets/6979737/21593698/84e301da-d0df-11e6-9c02-07c71c20cab7.png)

**Comment by ezekg** [comment]
Let me know if you need additional help.
