### ISSUE TITLE
Non-stop Flight Filter

### ISSUE THREAD

**Issue by tgevans0623** [ezekg/swa-dashboard#41]
This script is awesome!

Would be great if possible to incorporate SWA's non-stop filter. I have a handful of non-stops booked and would love to get notified if their prices drop, however a handful of flights on those same dates but with stops are already cheaper/less points. So I can't take advantage of the notification threshold for only the non-stop flights.

**Comment by ezekg** [comment]
Cool idea! Would you be interested in creating a PR that implements a `--non-stop` flag that enables the filtering? I don't have time to implement myself.

**Comment by tgevans0623** [comment]
I wish I could! I'm new to programming -- took me quite a lot of Googling to successfully follow the instructions and implement this script. Maybe somebody can, though!

I saw earlier the 'specific flight' request. This would be similar to that. Love the functionality so far though!

**Comment by ezekg** [comment]
Hey no problem! If you'd like to try and implement sometime (even if it's messy) I'd be more than happy to review and offer some feedback! Just let me know. 👍

**Comment by Gfriedman21** [comment]
https://github.com/ezekg/swa-dashboard/pull/44

**Comment by ezekg** [comment]
Merged.
