### ISSUE TITLE
time of day tags not working

### ISSUE THREAD

**Issue by LootenPlunder** [ezekg/swa-dashboard#48]
Adding --leave-time 'afternoon' doesn't have the desired effect, the search still says 'anytime' once the script runs. I can't seem to get any time of day flag to work for outbound or inbound. Also, I've traced the flag through index.js but I don't see where it's actually filtering the flights. (I could just be missing it)

**Comment by ezekg** [comment]
They're actually used [directly in within the form submission](https://github.com/ezekg/swa-dashboard/blob/master/index.js#L501-L502). It works for me using the command below,

```
swa --from DAL --to LGA --leave-date 6/5/2017 --return-date 6/6/2017 --leave-time morning --return-time evening --passengers 1
```

Could you send me what you're using so I can check it out?

**Comment by LootenPlunder** [comment]
Thanks. I was using apostrophes for my arguments, based on your response I took them out and it started working.

**Comment by ezekg** [comment]
Hmm, that's odd that it didn't work. Maybe your terminal was using curly quotes i.e. `‘’`?

**Comment by LootenPlunder** [comment]
I'm just using vanilla CMD, with `--leave-time 'evening'`. It would only work if I got rid of the quotes entirely.
