### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by geckert1** [ezekg/swa-dashboard#5]
I used npm link to install and it looks like it did but when I try to run the swa command with the flags, it says swa command not found. What am I missing? Please see screenshots.
<img width="1439" alt="screen shot 2017-01-02 at 1 31 27 pm" src="https://cloud.githubusercontent.com/assets/24880166/21594384/f38a22de-d0ef-11e6-83f1-2672847a86ff.png">

<img width="658" alt="screen shot 2017-01-02 at 1 31 44 pm" src="https://cloud.githubusercontent.com/assets/24880166/21594385/f38d87bc-d0ef-11e6-85c1-1d0de3023586.png">

**Comment by ezekg** [comment]
My guess would be that you don't have Node installed correctly (it shouldn't require `sudo` to link/install things). You can execute the `index.js` file directly by running these commands:

```bash
# 1. Change directory into where you installed the script
cd the-directory-that-contains-this-script
# 2. Make the index file executable
chmod +x index.js
# 3. Run the executable
./index.js --from a --to b etc…
```

**Comment by ezekg** [comment]
Let me know if you need additional help.
