### ISSUE TITLE
No flights found

### ISSUE THREAD

**Issue by LootenPlunder** [ezekg/swa-dashboard#50]
I downloaded and relinked the repo (I was running the version before telegram was added) and now any searches I do get 'no flights found' errors, whereas the same searches, which I have saved in .bat files on windows, worked fine before.

**Comment by caffeineflo** [comment]
Same here! Just went back to the commit at fcf4f6f4e4ed8075e755a83231af652da499caf7 and it worked again.

**Comment by ezekg** [comment]
@LootenPlunder and @caffeineflo what options are you using so I can test locally? Things are working fine for me using up-to-date master branch. I added validation so that searches that result `$Infinity` in the past (i.e. no results) now correctly say "no results."

**Comment by LootenPlunder** [comment]
I have both repo's and I jump back and forth by doing npm link in the folder I want to use, I haven't found a better way yet (windows). It works though, and I can use the same .bat file to run a command on either repo. in this case its:

```bash
@echo off

set TWILIO_ACCOUNT_SID=ACb09cf7ffb183e19235c4f2c8c448b385
set TWILIO_AUTH_TOKEN=d67cfdc608374b99d4f7a403c70da6e6
set TWILIO_PHONE_FROM=+17209032641
set TWILIO_PHONE_TO=+13039412641

mode con: cols=120 lines=36

swa --from MDW --to DEN --leave-date 07/10/2017 --leave-time evening --nonstop --passengers 1 --one-way --interval 60 --individual-deal-price 169
```

Using the old fork it works as expected, returning a price of $189. When I link the newest version I get the 'no flight info' error.

**Comment by ezekg** [comment]
Sorry—it looks like I broke the `one-way` flag when I added validation. I just pushed a fix. 👍

**Comment by LootenPlunder** [comment]
yup fixed now in up-do-date
