### ISSUE TITLE
Results are all $infinity

### ISSUE THREAD

**Issue by alexholliz** [ezekg/swa-dashboard#7]
Checking for a flight a few months out, but the results are all:
│ 01/02/17-18:18:36: Lowest fares for an outbound flight is currently $Infinity
│ 01/02/17-18:18:36: Lowest fares for an return flight is currently $Infinity

AFAIK the settings are all configured correctly, here's what I am using:
swa \
--from 'DAL' \
--to 'PDX' \
--leave-date '04-16-2017' \
--return-date '04-19-2017' \
--individual-deal-price 50 \
--passengers 2 \
--total-deal-price 150 \
--interval 0.1

**Comment by ezekg** [comment]
See https://github.com/ezekg/swa-dashboard/issues/4 for a similar issue. The `$Infinity` price means that the form submission failed. It looks like your dates are formatted wrong — format should be M/D/Y.

**Comment by swdgit** [comment]
I'm getting the same with the slashes.
`swa --from 'DEN' --to 'SJU' --leave-date '03/23/2017' --return-date '03/27/2017' --passengers --interval 1`

**Comment by xbenng** [comment]
i'm having the same issue, and I'm using the correct date format.

**Comment by jaredmichaelwilliams** [comment]
Same here

**Comment by jaredmichaelwilliams** [comment]
actually my mistake @xbenng was assuming that the airport i was picking had a South West airline in it. (Was using JFK instead of LGA)

Fixed it and its working now

**Comment by ezekg** [comment]
Cool. If anybody wants to add better validation, have at it!

**Comment by dannyreed** [comment]
Unfortunately I'm experiencing this issue with no obvious validation issues. Here's the exact command I am using to test:

`swa --from 'DAL' --to 'LGA' --leave-date '02/01/2016' --return-date '02/08/2016' --passengers 2 --individual-deal-price 50 --total-deal-price 120`

**Comment by solsenfinovertech** [comment]
It the date, you can't search for flights in the past. I also just ran into this 😀

**Comment by dannyreed** [comment]
Le sigh. Will take me about a month to adjust to 2017. Thanks!

**Comment by alexholliz** [comment]
For me; changing the date to slashes fixed the problem. Thanks everyone.
