### ISSUE TITLE
libxmljs does not work by default

### ISSUE THREAD

**Issue by pddenhar** [ezekg/swa-dashboard#8]
I thought this was a nifty project and wanted to make you aware of a possible issue relating to libxmljs and the solution. I know this isn't directly your problem, but it might save someone else some time debugging the issue or be worth mentioning briefly in the README to avoid being bugged in the future.

When trying to launch swa after `npm link` on both Ubuntu 16.04 and 14.04 using the latest nodejs installed from the node PPA, this error is thrown:

```
root@remote:~/swa-dashboard# swa
/root/swa-dashboard/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /root/swa-dashboard/node_modules/libxmljs/build/xmljs.node
...
...
```

This appears related to an outstanding issue in the libxml build: https://github.com/libxmljs/libxmljs/issues/253

You can fix it and run swa successfully by rebuilding libxml:

```
sudo npm install -g node-gyp
cd node_modules/libxmljs
node-gyp rebuild
```

**Comment by ezekg** [comment]
Appreciate the report! A pull request to update the readme is welcome.

**Comment by pddenhar** [comment]
No problem. While I was at it I added a line reminding people to upgrade node, which seems to be a common problem for users on Ubuntu, which ships a very old version by default that does not support the spread operator.

**Comment by ezekg** [comment]
Merged. ty
